/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaReedInterface */

#ifndef _Included_JavaReedInterface
#define _Included_JavaReedInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaReedInterface
 * Method:    update
 * Signature: (III[IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_JavaReedInterface_update
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jint, jint, jint);

/*
 * Class:     JavaReedInterface
 * Method:    updateSingleCode
 * Signature: (IIIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_JavaReedInterface_updateSingleCode
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     JavaReedInterface
 * Method:    recover
 * Signature: (III[I[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_JavaReedInterface_recover
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jintArray, jintArray);

/*
 * Class:     JavaReedInterface
 * Method:    addCodeWords
 * Signature: (I[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_JavaReedInterface_addCodeWords
  (JNIEnv *, jobject, jint, jintArray, jintArray);

/*
 * Class:     JavaReedInterface
 * Method:    addCodes
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JavaReedInterface_addCodes
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JavaReedInterface
 * Method:    encode
 * Signature: (III[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_JavaReedInterface_encode
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jintArray);

/*
 * Class:     JavaReedInterface
 * Method:    genRsMatrix
 * Signature: (III)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_JavaReedInterface_genRsMatrix
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     JavaReedInterface
 * Method:    genCauchyMatrix
 * Signature: (III)[I
 */
JNIEXPORT jintArray JNICALL Java_JavaReedInterface_genCauchyMatrix
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     JavaReedInterface
 * Method:    cauchyUpdate
 * Signature: ([I[I[III)[I
 */
JNIEXPORT jintArray JNICALL Java_JavaReedInterface_cauchyUpdate
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     JavaReedInterface
 * Method:    cauchyRecover
 * Signature: (IIII[I[I[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_JavaReedInterface_cauchyRecover
  (JNIEnv *, jobject, jint, jint, jint, jint, jintArray, jintArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
